### ISSUE TITLE
Beta release tracker

### ISSUE THREAD

**Issue by sadespresso** [flow-mn/flow#18]
Planned features for beta release

- [x] Adding transactions (income, expense)
- [x] Deleting transactions
- [x] #26
- [x] Creating, deleting accounts
- [x] [Upon setup, offer premade list of accounts, categories for smooth start](https://github.com/flow-mn/flow/issues/1)
- [x] #27
- [x] Export to JSON, recover data from backup file
- [x] Export to CSV for external software use

Plus, any issue with `Beta release` milestone
